spring:
  application:
    name: solo-leveling-ai
  kafka:
    bootstrap-servers: ${SERVER_HOST}:9092
    properties:
      schema.registry.url: http://${SERVER_HOST}:8081
  ai:
    openai:
      api-key: ${CHAT_TOKEN}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
